Avoid errors on values that cannot be `gsub!ed` or `strip!ed`.
Especially since the unescape nil casts to nil and one cannot gsub on
nil. Raising an `NoMethodError: undefined method `gsub!' for
nil:NilClass` exception.